llvm-config --system-libs can return absolute paths
tari/llvm-sys.rs pull request #11
Opened 2021-08-30 07:37 UTC by tchernobog

This is at least true for Debian Bullseye on my AMD64 system.

2021-09-02 05:27 UTC, tari requested changes

2021-09-02 05:27 UTC, tari commented on build.rs
> +                let maybe_lib = Path::new(&flag);
Can we move things around some to avoid creating this unless it's needed? I'm thinking have the `-l` branch explicitly return, then `maybe_lib` doesn't need to be initialized before that check.

2021-09-03 08:06 UTC, tchernobog commented on build.rs
> +                let maybe_lib = Path::new(&flag);
I am a bit unsure if this helps readability, but I carried out the change as requested. Thanks!

2021-09-04 03:52 UTC, tari commented on build.rs
> +                let maybe_lib = Path::new(&flag);
Yeah, I think it's a little nicer- setting up a temporary before a branch in which it was completely unused seemed confusing.

2021-09-04 03:52 UTC, merged

2021-09-04 03:56 UTC, tari commented
Did you need this backported to any particular crate release?

2021-09-04 11:20 UTC, tchernobog commented
> Did you need this backported to any particular crate release?

I needed this in the scope of compiling `cargo-bpf` (inside `redbpf`), which relies on llvm-sys 110 and 120. However I don't personally use the llvm-sys 110 support. I think it'd be enough to have this for the 120 release series, but if you have the time to backport it for the 110 release, it'd be awesome.